### ISSUE TITLE
Default redirect is not permanent (301)

### ISSUE THREAD

**Issue by KeitIG** [thenativeweb/forcedomain#11]
Hi, 

I've just testest forcedomain, but I got an issue:

``` javascript
// forcedomain
app.use(force({
    hostname : 'mywebsite.com'
}));
```

make a 307 redirect, for a 301 redirect, I needed to 

``` javascript
app.use(force({
    hostname : 'mywebsite.com',
    type     : 'permanent' 
}));
```

Is that the default behavior ?

**Comment by goloroden** [comment]
Thanks for pointing this out, this is a bug.

In [this line](https://github.com/thenativeweb/forcedomain/blob/49637fc087aa6111c4b5e6abe7ddcc09a79068b9/lib/redirect.js#L16) it should be `permanent`, not `temporary` as default value.

Would you mind changing it, adjusting the tests, and sending a PR?
