### ISSUE TITLE
Infinite redirect loop - on cloudfront, https

### ISSUE THREAD

**Issue by jgrisafe** [thenativeweb/forcedomain#19]
I'm getting an infinite redirect loop - using cloudfront to force ssl. Anyone experienced this?

**Comment by goloroden** [comment]
Unfortunately, no, I haven't experienced this, but maybe someone else did?

(Apart from not having experienced this, can you provide a little more detail? Which domain? How did you configure forcedomain? …? Maybe we can figure the problem out anyway)

**Comment by jgrisafe** [comment]
Hey @goloroden thanks for the reply. I figured out that I was not forwarding the host header from Cloudfront. Thus, the node application was receiving a null value for the host, and would continue to redirect the client to the default domain, even though it was already there. Rookie mistake, but it may not hurt to write something in the readme about forwarding the host header when using CDNs.

**Comment by goloroden** [comment]
Hey, no problem 😊 

It's great that you figured it out!
Would you mind adding a comment to the `README.md` file and sending a PR?

**Comment by goloroden** [comment]
I'm closing this as the issue itself was resolved, and there is no further activity any more in this issue.
