### ISSUE TITLE
Only root?

### ISSUE THREAD

**Issue by AndreaBarbon** [thenativeweb/forcedomain#26]
It seems like this works for the root of the website but not for other urls., e.g.

https://risiko.online      --> https://www.risiko.online
https://risiko.online/demo --> https://risiko.online/demo

Is this the expected behavior or am I doing something wrong?

Thanks!! :-)

**Comment by AndreaBarbon** [comment]
I'm sorry, the problem comes surely from my nginx configuration, which I never understood completely:

```
server {

    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name xxx.xxx.xxx.xxx risiko.online *.risiko.online;

    ssl_certificate           /home/...
    ssl_certificate_key       /home/...

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    location / {

      root /home/...;
      proxy_set_header X-Forwarded-Host $host:$server_port;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_pass          http://127.0.0.1:8081;
      proxy_read_timeout  90;

      proxy_redirect      http://127.0.0.1:8081 https://www.risiko.online;
    }
  }
```

Adding the line you suggest (`proxy_set_header Host $http_host`) seems  to break everything. 

Would you be so kind to help me on this? Thanks!!!

**Comment by goloroden** [comment]
Unfortunately, I'm not an expert in NGinx, so this is a little bit out of scope for this module. Sorry :-(
