### ISSUE TITLE
Adding `dev` option to support `lvh.me`

### ISSUE THREAD

**Issue by dcangulo** [thenativeweb/forcedomain#74]
I use `lvh.me` since my app has subdomain and I can't use `localhost`, `127.0.0.1`, nor `192.168.x.x` for that. In my production and staging environment, this package works well on redirecting non-www to www.

Code:
```js
app.use(forceDomain({ hostname: `www.${host}` }));
```

But in my dev environment, I am getting too many redirects error. For it to work on dev, I need to add `port: 3001` and make sure to not commit it.

I am thinking that we can add another option like this:

```js
forceDomain({ dev: process.env.NODE_ENV === 'development' });
```

Where `dev` option is a boolean, that if it's a dev environment don't use forcedomain.

I think the condition can be added here:
https://github.com/thenativeweb/forcedomain/blob/master/lib/redirect.ts#L20

This way we can make use of `process.env.NODE_ENV` variable for the value of `dev`.

What do you think? I can work on this if it's welcome.

If not I will just create a condition on my app to use port if it's dev.

**Comment by goloroden** [comment]
Hey @dcangulo 👋

Thanks for bringing up this issue, and I actually like your idea. The only little thing I‘d like to change in your suggestion is that we rename `dev` to `isEnabled`: This way we decouple the fact whether the module is enabled or not from the question whether we are running in development mode, and it‘s possible for the user to use whatever she or he wants to use as a condition.

If you‘re fine with this, and want to come up with a PR, we would highly appreciate that 😊

Cheers,


Golo
