### ISSUE TITLE
No port in `Host` headers versus port 80 in options

### ISSUE THREAD

**Issue by robertklep** [thenativeweb/forcedomain#8]
(some background [in this SO comment](http://stackoverflow.com/questions/31137364/redirect-loop-when-setting-port-via-environment-variable-in-forcedomain-node-js/31159298#comment50523387_31159298))

When an incoming request doesn't have a port number in the `Host` header, `forcedomain` uses a value of `undefined` to match against the port value passed in the options. This means that setting a port value of `80` in the options will cause redirect loops (because `undefined !== 80`).

This behaviour is _somewhat_ documented, but not very explicitly. I think that most users will assume that passing `port : 80` works just like it does with any other port number.

FWIW, passing a string value as port number also yields unexpected behaviour (which was the reason for the abovementioned SO question being asked to begin with).

**Comment by hooke** [comment]
Confirming the importance of the issue as the topicstarter of abovementioned [SO question](http://stackoverflow.com/questions/31137364/redirect-loop-when-setting-port-via-environment-variable-in-forcedomain-node-js)

**Comment by goloroden** [comment]
Thanks for the issue and sorry for replying that late.

We will have a look at it within the next few days and provide a fix.
(Of course, we are also happy about a PR ;-))

**Comment by goloroden** [comment]
@hooke Would you mind creating a PR with the solution that you proposed on StackOverflow?

**Comment by hooke** [comment]
Of course not. How can I help with such a PR?

**Comment by goloroden** [comment]
@hooke Great :-)

Well, I think the easiest way would be that you

- fork this repo,
- add your solution from SO,
- and then send a PR so I can merge it.

Is this okay for you?

**Comment by hooke** [comment]
@goloroden - ok
I'll do this in about a week, currently have no extra time for this :(

**Comment by goloroden** [comment]
This is great news, thanks a lot :-))

(And don't hurry, I'm very glad that you'll do it :-))

**Comment by raistlinthewiz** [comment]
any updates on this?

**Comment by goloroden** [comment]
Unfortunately no. If you want to create a PR, I'd be more than happy to merge it :-)

**Comment by veera83372** [comment]
@goloroden  It's been a long time from above comments.
Would you mind If I create PR?

**Comment by goloroden** [comment]
Not at all - actually I‘d be more than happy to merge one 😊

**Comment by veera83372** [comment]
Hey @goloroden,
I think I am not clear about this Can you please explain what is the problem with this issue?

**Comment by goloroden** [comment]
What is unclear with the OP‘s explanation?

**Comment by veera83372** [comment]
When there is no port in host headers and 80 specified in options its working fine for me.
Its not creatig redirection loop

**Comment by goloroden** [comment]
Maybe then this issue is not relevant any more, as it was fixed meanwhile (please note that the original issue is from 2015!).

Would you mind adding a test for this behavior to prove that it's working correctly, and submitting that test as PR?

**Comment by veera83372** [comment]
Okay @goloroden

**Comment by goloroden** [comment]
This has been fixed at some point in time between 2015 and 2018, and thanks to @veera83372 we now have a test to prove that it works 😊
